### PR TITLE
Created Third Template

### PR DESCRIPTION
**Pull request by A1X5H04**
created third template for the resume builder website
image

### CODE REVIEW

**Review by hardikd-zignuts — CHANGES_REQUESTED** [review]
Hello @A1X5H04 ,
Can You Remove Import warnings, because it will give an error in the deployment

**Comment by A1X5H04** [comment]
> Hello @A1X5H04 , Can You Remove Import warnings, because it will give an error in the deployment

Sure, but you could you point out which line ?

**Comment by imhardikdesai** [comment]
@A1X5H04 you can refer this deployment log https://app.netlify.com/sites/quick-resume/deploys/6513c97dabba8f0009d3889b

**Comment by A1X5H04** [comment]
> @A1X5H04 you can refer this deployment log https://app.netlify.com/sites/quick-resume/deploys/6513c97dabba8f0009d3889b

fixed, you may merge

**Comment by imhardikdesai** [comment]
Thank you @A1X5H04 for you contribution 😄

**Comment by A1X5H04** [comment]
@imhardikdesai Thanks!

**Pull request merged**
